<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Fiscalización de reposo · SDI</title>
<style>
:root{--ink:#183442;--teal:#0b879d;--line:#d6e2e6;--muted:#667b84}*{box-sizing:border-box}body{margin:0;background:#eef4f5;color:var(--ink);font-family:Arial,sans-serif}.top{display:flex;align-items:center;justify-content:space-between;padding:18px 28px;background:#123847;color:#fff}.top a{color:#fff}.wrap{max-width:1250px;margin:auto;padding:24px}.hero,.panel{background:#fff;border:1px solid var(--line);border-radius:14px;padding:22px;margin-bottom:18px}.hero{background:#115565;color:#fff}.hero h1{margin:4px 0 8px}.hero p{margin:0;color:#d7edf1}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}label{font-size:12px;font-weight:700;color:var(--muted)}input,textarea{display:block;width:100%;margin-top:6px;padding:11px;border:1px solid #bfd0d5;border-radius:8px}.full{grid-column:1/-1}.button{display:inline-block;border:0;border-radius:8px;padding:11px 15px;background:var(--teal);color:#fff;font-weight:700;text-decoration:none;cursor:pointer}.permissions{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:14px 0}.permissions div{padding:12px;border-radius:9px;background:#edf7f8;font-weight:700}.ok{padding:12px;border-radius:8px;background:#daf3e7;color:#176440;margin-bottom:16px}.errors{padding:12px;border-radius:8px;background:#fde2e4;color:#8a2730;margin-bottom:16px}table{width:100%;border-collapse:collapse}th,td{padding:11px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top}th{font-size:11px;text-transform:uppercase;color:var(--muted)}small{display:block;color:var(--muted);margin-top:4px}.badge{display:inline-block;padding:5px 9px;border-radius:99px;background:#edf3f5}.pending{background:#fff1c9}.approved{background:#daf3e7}.rejected{background:#fde2e4}.decision{display:grid;grid-template-columns:repeat(3,minmax(100px,1fr));gap:5px}.decision span{font-size:11px;padding:5px;border-radius:5px;background:#edf3f5}@media(max-width:720px){.grid,.permissions{grid-template-columns:1fr}.decision{grid-template-columns:1fr}.full{grid-column:auto}.table{overflow:auto}}
</style></head><body>
<header class="top"><strong>SDI · Administración y Fiscalización</strong><a href="{{ route('demo.index') }}">← Volver al portal</a></header>
<main class="wrap">
<section class="hero"><small>FISCALIZACIÓN DE REPOSO</small><h1>Solicitudes al paciente</h1><p>Este escritorio y la app comparten la misma API y la misma base de datos.</p></section>
@if(session('ok'))<div class="ok">{{ session('ok') }}</div>@endif
@if($errors->any())<div class="errors">@foreach($errors->all() as $error)<div>{{ $error }}</div>@endforeach</div>@endif
<section class="panel"><h2>Nueva solicitud</h2><p>El paciente decidirá cada permiso de forma independiente.</p>
<div class="permissions"><div>1. Antecedentes</div><div>2. Ubicación y Google Maps</div><div>3. Cámara</div></div>
<form method="POST" action="{{ route('fiscalizacion.store') }}" class="grid">@csrf
<label>RUT del paciente<input name="paciente_rut" value="{{ old('paciente_rut','12.345.678-9') }}" required></label>
<label>Nombre del paciente<input name="paciente_nombre" value="{{ old('paciente_nombre','Paciente Demo') }}" required></label>
<label>Folio opcional<input name="folio" value="{{ old('folio') }}" placeholder="Se genera automáticamente"></label>
<label>Días de reposo<input type="number" min="1" max="365" name="dias_reposo" value="{{ old('dias_reposo',7) }}" required></label>
<label>Inicio del reposo<input type="date" name="fecha_inicio_reposo" value="{{ old('fecha_inicio_reposo',now()->toDateString()) }}"></label>
<label class="full">Motivo de la fiscalización<textarea name="motivo">{{ old('motivo','Verificación de cumplimiento del reposo indicado.') }}</textarea></label>
<div class="full"><button class="button">Enviar solicitud a la app</button></div></form></section>
<section class="panel"><h2>Seguimiento de respuestas</h2><div class="table"><table><thead><tr><th>Solicitud</th><th>Paciente</th><th>Estado</th><th>Decisiones independientes</th><th>Fecha</th></tr></thead><tbody>
@forelse($solicitudes as $solicitud) @php($payload=$solicitud->payload_app ?: []) @php($decisiones=$payload['decisiones'] ?? [])
<tr><td><strong>{{ optional($solicitud->expediente)->folio }}</strong><small>{{ $solicitud->token }}</small></td><td>{{ optional(optional($solicitud->expediente)->paciente)->nombre }}<small>{{ optional(optional($solicitud->expediente)->paciente)->rut }}</small></td><td><span class="badge {{ $solicitud->estado }}">{{ ucfirst($solicitud->estado) }}</span><small>{{ $solicitud->respuesta_observacion }}</small></td><td><div class="decision"><span>Antecedentes: {{ array_key_exists('antecedentes',$decisiones) ? ($decisiones['antecedentes']?'Autorizado':'Rechazado') : 'Pendiente' }}</span><span>Ubicación: {{ array_key_exists('ubicacion',$decisiones) ? ($decisiones['ubicacion']?'Autorizada':'Rechazada') : 'Pendiente' }}</span><span>Cámara: {{ array_key_exists('camara',$decisiones) ? ($decisiones['camara']?'Autorizada':'Rechazada') : 'Pendiente' }}</span></div></td><td>{{ optional($solicitud->solicitada_at)->format('d-m-Y H:i') }}<small>@if($solicitud->respondida_at)Respondida {{ $solicitud->respondida_at->format('d-m-Y H:i') }}@endif</small></td></tr>
@empty<tr><td colspan="5">Aún no hay solicitudes de fiscalización.</td></tr>@endforelse
</tbody></table></div></section></main></body></html>
