@extends('demo.layout')
@section('content')
<h1>{{ \App\Services\DemoLicenciaService::ROLES[$role] }}</h1>
@if($role==='contraloria')
<section class="panel"><h2>Parámetros de revisión automática</h2><p>Se revisan los expedientes activos al registrar acciones o guardar estos parámetros. Solo los incumplimientos, datos insuficientes y alertas requieren revisión humana.</p><form method="POST" action="/demo/contraloria/parametros">@csrf<div class="form-grid">
@foreach(['radius_km'=>['Radio desde el lugar de reposo (km)',0.1,100,0.1],'review_from'=>['Revisar desde la licencia N.º del paciente (0 desactiva)',0,1000,1],'max_days'=>['Máximo de días de reposo sin revisión',1,365,1],'min_minutes'=>['Mínimo de minutos de consulta (0 desactiva)',0,240,1],'max_accuracy'=>['Máxima imprecisión de ubicación (metros)',1,10000,1]] as $key=>$field)<label>{{ $field[0] }}<input type="number" name="{{ $key }}" min="{{ $field[1] }}" max="{{ $field[2] }}" step="{{ $field[3] }}" value="{{ $reviewSettings[$key] }}" required></label>@endforeach
<label class="checkbox"><input type="checkbox" name="check_location" value="1" @checked($reviewSettings['check_location'])> Evaluar ubicación y radio</label><label class="checkbox"><input type="checkbox" name="check_origin" value="1" @checked($reviewSettings['check_origin'])> Exigir primer filtro completo: bono, habilitación y relación de atención</label></div><details open><summary>Controles cruzados por actor</summary><div class="form-grid">@foreach(\App\Services\RiskControlService::RULES as $key=>$label)<label class="checkbox"><input type="checkbox" name="risk_rules[{{ $key }}]" value="1" @checked($reviewSettings['risk_rules'][$key]??true)> {{ $label }}</label>@endforeach</div><div class="form-grid">@foreach(\App\Services\RiskControlService::NUMBERS as $key=>$meta)<label>{{ $meta[0] }}<input type="number" name="{{ $key }}" min="{{ $meta[2] }}" max="{{ $meta[3] }}" value="{{ $reviewSettings[$key]??$meta[1] }}" required></label>@endforeach</div></details><button class="button">Guardar y reevaluar expedientes</button></form><p class="fine">Número de licencia: historial del paciente en este demo, excluye borradores y canceladas. Los casos pagados no se modifican. Umbrales operativos de demostración, no límites legales.</p></section>
<h2>Casos que requieren revisión</h2>
@php($cases=$cases->filter(fn($c)=>($c->data['auto_review']['requires_review']??false)||$c->data['hold']||in_array($c->status,['revision','apelacion'])))
@endif
@if($role==='paciente')
<section class="panel"><h2>Conexión con la app del paciente</h2><p>Recibe la solicitud del profesional y aprueba o rechaza su envío.</p><details><summary>Preparar solicitud de ejemplo</summary><form method="POST" action="/demo/circuito/preparar">@csrf<label>Paciente<select name="patient_id" required>@foreach($patients as $p)<option value="{{ $p->id }}">{{ $p->name }}</option>@endforeach</select></label><button class="button">Simular emisión y avisar al paciente</button></form><small>Crea un caso ficticio con controles de origen simulados y un empleador asignado.</small></details></section>
@endif
@if($role!=='paciente')<details class="panel"><summary>Identidad del operador de demostración</summary><form method="POST" action="/demo/riesgos/operador">@csrf<label>Identificador de cuenta demo<input name="operator" required pattern="[a-zA-Z0-9_-]{3,40}" value="{{ session('demo_operator_id',$role.'-demo') }}"></label><button class="button secondary">Usar operador</button></form><p class="fine">Permite probar funciones incompatibles. Estos identificadores son simulados; se necesita autenticación real para aplicarlo en producción.</p></details>@endif
@forelse($cases as $case)
@php($d=$case->data)
<section class="panel"><div class="section-head"><h2>{{ $d['patient'] }}</h2><span class="badge">{{ \App\Services\DemoLicenciaService::STATES[$case->status] }}</span></div><small>{{ $case->folio }}</small>
@if($role==='paciente')
<div class="phone-card"><p><strong>{{ $d['doctor'] }}</strong> está emitiendo una licencia de reposo por <strong>{{ $d['days'] }} días</strong>, desde {{ $d['start'] }}, en <strong>{{ $d['address'] }}</strong>.</p><a class="button" href="{{ \App\Http\Controllers\DemoAppController::link($case) }}" target="_blank" rel="noopener">Abrir app para aprobar o rechazar</a>
@if($case->status==='paciente')<div class="action-row">@foreach(['autorizar'=>'Simular aprobación','no_autorizar'=>'Simular rechazo'] as $a=>$label)<form method="POST" action="{{ url('/demo/circuito/'.$case->id.'/accion') }}">@csrf<input type="hidden" name="version" value="{{ $case->version }}"><input type="hidden" name="action" value="{{ $a }}"><button class="button {{ $a==='no_autorizar'?'secondary':'' }}">{{ $label }}</button></form>@endforeach</div>@elseif($case->status==='cancelada')<p class="notice warning">Rechazaste el envío. El proceso está detenido.</p>@elseif($case->status==='borrador')<p class="notice">Pendiente de emisión y controles del profesional.</p>@else<p class="notice success">Tu respuesta ya está registrada. Estado: {{ \App\Services\DemoLicenciaService::STATES[$case->status] }}.</p>@endif</div>
@elseif($role==='empleador')
<h3>{{ $d['employer'] }}</h3><p>Preparar las tres liquidaciones previas al inicio del reposo, cotizaciones de seis meses, contrato e historial de licencias.</p>
@if($case->status==='empleador')<form method="POST" action="{{ url('/demo/circuito/'.$case->id.'/accion') }}">@csrf<input type="hidden" name="version" value="{{ $case->version }}"><input type="hidden" name="action" value="antecedentes"><button class="button">Simular antecedentes y enviar a revisión</button></form>@elseif($case->status==='cancelada')<p class="notice warning">Proceso detenido por el paciente. No se pueden enviar antecedentes.</p>@else<p>Esperando la etapa correspondiente o antecedentes ya enviados.</p>@endif
@foreach($d['documents'] as $key=>$document)<p><a href="{{ route('demo.document',[$case,$key]) }}" target="_blank">{{ $document['name'] }}</a></p>@endforeach
@elseif($role==='pagador')
<p>{{ $d['payer']??($d['insurance'].' · entidad pagadora simulada') }}</p>
@if($case->status==='revision')<p class="notice">Antecedentes recibidos. El pago está bloqueado hasta el dictamen favorable de Contraloría.</p><form method="POST" action="{{ route('demo.role') }}">@csrf<input name="role" type="hidden" value="contraloria"><button class="button">Ir a Contraloría para simular dictamen</button></form>
@elseif(in_array($case->status,['aprobada','reducida']))<form method="POST" action="{{ url('/demo/circuito/'.$case->id.'/accion') }}">@csrf<input type="hidden" name="version" value="{{ $case->version }}"><input type="hidden" name="action" value="pagar"><button class="button">Simular cálculo y pago</button></form>
@elseif($case->status==='pagada')<p class="notice success">Pago simulado: ${{ number_format($d['payment']['amount'],0,',','.') }}</p><a href="{{ route('demo.receipt',$case) }}">Ver comprobante</a>
@else<p class="notice">Sin autorización para pagar en el estado actual.</p>@endif
@elseif(in_array($role,['contraloria','auditor','admin']))
@if(isset($d['auto_review']))<div class="notice {{ $d['auto_review']['requires_review']?'warning':'success' }}"><strong>{{ $d['auto_review']['requires_review']?'Revisión requerida':'Parámetros cumplidos' }}</strong><ul>@foreach($d['auto_review']['reasons'] as $reason)<li>{{ $reason }}</li>@endforeach</ul></div>@endif
@if($role==='contraloria')<details><summary>Referencia del lugar de reposo para calcular el radio</summary><p>{{ $d['address'] }}</p><form method="POST" action="{{ url('/demo/contraloria/'.$case->id.'/referencia') }}">@csrf<label>Latitud del domicilio<input name="latitude" type="number" step="any" min="-90" max="90" value="{{ $d['rest_coordinates']['latitude']??'' }}" required></label><label>Longitud del domicilio<input name="longitude" type="number" step="any" min="-180" max="180" value="{{ $d['rest_coordinates']['longitude']??'' }}" required></label><button class="button">Guardar referencia y reevaluar</button></form></details>@endif
<p>Consentimiento: {{ $d['consent']?'Sí':'No' }} · Documentos: {{ count($d['documents']) }} · Alerta: {{ $d['hold']?'Pendiente':'Sin alerta activa' }}</p>
@if($role==='contraloria'&&$case->status==='revision')<form method="POST" action="{{ url('/demo/circuito/'.$case->id.'/accion') }}">@csrf<input type="hidden" name="version" value="{{ $case->version }}"><input type="hidden" name="action" value="dictamen"><button class="button">Simular revisión y dictamen favorable</button></form>@endif
<a href="{{ route('demo.show',$case) }}">Revisar expediente, primer filtro y trazabilidad</a>
@if($role==='contraloria' && $d['consent'] && !in_array($case->status,['cancelada','rechazada']))
<details><summary>Solicitar autorización en la app del paciente</summary><form method="POST" action="{{ route('demo.action',$case) }}">@csrf<input type="hidden" name="version" value="{{ $case->version }}"><input type="hidden" name="action" value="solicitar_control"><label>Permiso<select name="kind"><option value="ubicacion">Ubicación puntual</option><option value="camara">Cámara</option><option value="ficha">Ficha clínica</option></select></label><label>Motivo<textarea name="note" required minlength="10"></textarea></label><button class="button">Enviar solicitud a la app</button></form></details>
@endif
@foreach($d['control_requests']??[] as $request)<p><strong>{{ ucfirst($request['kind']) }}:</strong> {{ $request['status'] }} · {{ $request['reason'] }}<small>{{ $request['responded_at']??'Esperando respuesta del paciente' }}</small></p>@endforeach
@endif
@include('demo.risk-evidence')
</section>
@empty<div class="panel">No hay solicitudes registradas. En Paciente puedes preparar una solicitud de ejemplo.</div>@endforelse
@if(in_array($role,['contraloria','auditor','admin']))<section class="panel"><h2>Fiscalización del proceso en el backend</h2><div class="tablebox"><table><tr><th>Fecha UTC</th><th>Expediente</th><th>Actor / canal</th><th>Acción</th><th>Resultado</th><th>Control</th></tr>@forelse($logs as $log)<tr><td>{{ $log->created_at }}</td><td>{{ $log->folio }}</td><td>{{ $log->role }} / {{ $log->channel }}</td><td>{{ ['evaluar_parametros'=>'Evaluación automática','ajustar_parametros'=>'Cambio de parámetros','fijar_referencia_reposo'=>'Referencia de reposo','pagar'=>'Registrar pago','enviar'=>'Enviar antecedentes','autorizar'=>'Aprobar envío','no_autorizar'=>'Rechazar envío','emitir'=>'Emitir licencia','dictamen'=>'Registrar dictamen','responder_control'=>'Respuesta del paciente','solicitar_control'=>'Solicitar control'][$log->action] ?? ucfirst(str_replace('_',' ',$log->action)) }}</td><td><span class="badge">{{ ['revision'=>'Requiere revisión','cumple'=>'Cumple','aceptado'=>'Aceptado','bloqueado'=>'Bloqueado'][$log->result] ?? $log->result }}</span></td><td>
@php($control=json_decode($log->reason??'',true))
@if(is_array($control))
@if(isset($control['reasons']))
<strong>{{ ($control['requires_review']??false)?'Requiere revisión':'Controles cumplidos' }}</strong>
@forelse($control['reasons'] as $reason)<p style="margin:5px 0">{{ $reason }}</p>@empty<p style="margin:5px 0">No se detectaron incumplimientos con los parámetros evaluados.</p>@endforelse
@if(isset($control['license_number']))<small>Licencia N.º {{ $control['license_number'] }} del paciente.</small>@endif
@if(isset($control['distance_km']))<small>Distancia al lugar de reposo: {{ number_format($control['distance_km'],2,',','.') }} km.</small>@endif
@endif
@php($parameters=$control['parameters']??$control)
<details><summary>Parámetros utilizados</summary><dl>
@foreach(['radius_km'=>['Radio permitido',' km'],'review_from'=>['Revisar desde licencia N.º',''],'max_days'=>['Máximo de reposo sin revisión',' días'],'min_minutes'=>['Duración mínima de consulta',' minutos'],'max_accuracy'=>['Máxima imprecisión de ubicación',' m'],'check_origin'=>['Verificar primer filtro',''],'check_location'=>['Verificar ubicación','']] as $key=>$label)
@if(array_key_exists($key,$parameters))<dt>{{ $label[0] }}</dt><dd>{{ in_array($key,['check_origin','check_location'])?($parameters[$key]?'Activado':'Desactivado'):($parameters[$key].$label[1]) }}</dd>@endif
@endforeach</dl></details>
@else{{ $log->reason }}@endif
</td></tr>@empty<tr><td colspan="6">Sin transiciones registradas.</td></tr>@endforelse</table></div></section>@endif
@if(in_array($role,['contraloria','auditor','admin']))<section class="panel" id="auditoria"><h2>Avisos del primer filtro</h2>@forelse($filterAudits as $audit)<details><summary>{{ $audit->passed?'Superado':'No superado' }} · {{ $audit->folio }} · {{ $audit->reviewed_at?'Revisado':'Pendiente' }}</summary><p>{{ $audit->patient_notification }}</p>@if(!$audit->reviewed_at && in_array($role,['contraloria','auditor']))<form method="POST" action="{{ url('/demo/auditoria/'.$audit->id.'/revisar') }}">@csrf<label>Observación<textarea name="note" required></textarea></label><button class="button">Registrar revisión</button></form>@else<p>{{ $audit->review_note }}</p>@endif</details>@empty<p>Sin evaluaciones registradas.</p>@endforelse</section>@endif
@if($role!=='paciente')<p class="fine">Circuito simulado de enfermedad común para dependientes privados. Referencia: <a href="https://www.suseso.gob.cl/606/w3-propertyvalue-351151.html" target="_blank" rel="noopener">Guía SUSESO</a>. Las validaciones del demo no certifican cumplimiento normativo integral ni verifican afiliación o documentos reales. El pago es estimativo.</p>@endif
@endsection
