@php($e=$d['risk_evidence']??[])
@if(in_array($role,['admin','contraloria','auditor']))
<details><summary>Resultados de controles cruzados</summary>
@forelse($d['auto_review']['checks']??[] as $check)<div class="notice {{ $check['severity']==='bloqueo'?'error':'warning' }}"><strong>{{ \App\Services\RiskControlService::RULES[$check['code']]??$check['code'] }}</strong><p>{{ $check['reason'] }}</p><small>Responsable: {{ $check['actor'] }} · {{ $check['severity']==='bloqueo'?'Bloqueo técnico':'Revisión humana' }}</small><dl>@foreach($check['evidence'] as $label=>$value)<dt>{{ ucfirst(str_replace('_',' ',$label)) }}</dt><dd>{{ is_array($value)?implode(' · ',array_map(fn($v)=>is_array($v)?implode(' / ',array_values($v)):$v,$value)):($value??'Sin datos') }}</dd>@endforeach</dl></div>@empty<p>No se han registrado señales de controles cruzados.</p>@endforelse
@foreach($d['risk_explanations']??[] as $explanation)<p><strong>Explicación de {{ $explanation['role'] }}:</strong> {{ $explanation['text'] }}<small>{{ $explanation['at'] }}</small></p>@endforeach
</details>
@endif
@if(in_array($role,['admin','profesional','empleador','contraloria','pagador'])&&!in_array($case->status,['pagada','cancelada']))
<details><summary>Antecedentes para controles cruzados · demo</summary><form method="POST" action="{{ url('/demo/riesgos/'.$case->id.'/evidencia') }}">@csrf<input type="hidden" name="version" value="{{ $case->version }}"><div class="form-grid">
@if(in_array($role,['admin','contraloria','empleador']))
@foreach(['contract_start'=>'Inicio de contrato','affiliation_start'=>'Inicio de afiliación'] as $key=>$label)<label>{{ $label }}<input type="date" name="{{ $key }}" value="{{ $e[$key]??'' }}"></label>@endforeach
<label>Identificador del empleador ficticio<input name="employer_id" value="{{ $e['employer_id']??'' }}"></label>
@foreach(['contract_net'=>'Remuneración neta del contrato','previous_net'=>'Remuneración neta anterior al período','payroll_gross'=>'Promedio imponible de liquidaciones','contribution_gross'=>'Promedio imponible de cotizaciones del mismo período'] as $key=>$label)<label>{{ $label }}<input type="number" name="{{ $key }}" min="1" max="100000000" value="{{ $e[$key]??'' }}"></label>@endforeach
@endif
@if(in_array($role,['admin','contraloria','pagador']))<label>Identificador del destinatario del pago<input name="recipient_id" value="{{ $e['recipient_id']??'' }}"></label><label class="checkbox"><input type="checkbox" name="recipient_verified" value="1" @checked($e['recipient_verified']??false)> Destinatario verificado en el demo</label><p class="fine">Cambiar el destinatario revoca la verificación; confirma de nuevo después de comprobarlo.</p>@endif
@if(in_array($role,['admin','contraloria','profesional']))<label>Relación con otra licencia<select name="leave_relation">@foreach(['normal'=>'Independiente','continuacion'=>'Continuación','reemplazo'=>'Reemplazo','varios_empleadores'=>'Múltiples empleadores'] as $key=>$label)<option value="{{ $key }}" @selected(($d['leave_relation']??'normal')===$key)>{{ $label }}</option>@endforeach</select></label><label>ID de licencia relacionada del mismo paciente<input name="related_case_id" type="number" min="1" value="{{ $d['related_case_id']??'' }}"></label><label>Fundamento de la relación<textarea name="relation_explanation">{{ $d['relation_explanation']??'' }}</textarea></label>
@else<input type="hidden" name="leave_relation" value="normal">@endif
</div><label>Fundamento y respaldo de estos antecedentes<textarea name="explanation" required minlength="10" maxlength="1500"></textarea></label><button class="button">Guardar evidencia y reevaluar</button></form></details>
@if($role==='contraloria'&&!empty($d['documents']))<details><summary>Revalidar antecedentes modificados</summary><form method="POST" action="{{ url('/demo/riesgos/'.$case->id.'/revalidar') }}">@csrf<input type="hidden" name="version" value="{{ $case->version }}"><label>Qué se comprobó y fundamento de la revalidación<textarea name="note" required minlength="20" maxlength="1500"></textarea></label><button class="button secondary">Registrar nueva verificación</button></form></details>@endif
@endif
@if($role==='paciente')<details><summary>Explicar una observación de reposo o control</summary><form method="POST" action="{{ url('/demo/riesgos/'.$case->id.'/explicacion') }}">@csrf<label>Explicación para Contraloría<textarea name="note" minlength="10" maxlength="1500" required></textarea></label><button class="button">Enviar explicación</button></form><small>Estar fuera del radio o rechazar un permiso no prueba fraude ni rechaza automáticamente la licencia.</small></details>@endif
