@extends('demo.layout')
@section('title', $case->folio.' · Demo SDI')
@section('content')
@if(!empty($d['filter_notification']))<div class="notice warning" role="alert"><strong>Notificación al paciente · primer filtro</strong><p>{{ $d['filter_notification'] }}</p></div>@endif
@if(isset($d['first_filter']))
<section class="panel"><h2>Primer filtro · paciente, profesional y lugar de atención</h2><p class="notice">{{ $d['first_filter_passed'] ? 'Controles de origen completos en el demo.' : 'Pendiente: revisa la hora, el bono y la concordancia de modalidad antes de emitir.' }}</p><dl>@foreach($d['first_filter'] as $label=>$value)<dt><strong>{{ $label }}</strong></dt><dd>{{ $value }}</dd>@endforeach</dl><p class="fine">Indicadores al preparar este borrador; licencias ya emitidas, excluye la actual. Día y mes corresponden a la fecha de consulta. Sin umbrales de bloqueo por volumen.</p>@if($case->status==='borrador')<a class="button secondary" href="{{ url('/?edit='.$d['consultation_id']).'#atencion' }}">Editar atención de origen</a>@endif</section>
@endif
<a class="back" href="{{ route('demo.index') }}">← Todos los expedientes</a>
<div class="panel"><div class="section-head"><div><div class="eyebrow">APP CONECTADA</div><h2>Control de licencias del paciente</h2></div><a class="button" href="{{ \App\Http\Controllers\DemoAppController::link($case) }}" target="_blank" rel="noopener">Abrir app de control ↗</a></div><p class="fine">La app y este portal comparten el expediente. Las autorizaciones y controles se guardan en el servidor. Actualiza el portal para ver las acciones de la app.</p><details><summary>Vincular desde otro dispositivo</summary><label>Enlace para pegar en la app<input readonly value="{{ \App\Http\Controllers\DemoAppController::link($case) }}" onclick="this.select()"></label><p class="fine">El enlace da acceso de paciente a este caso ficticio. El otro dispositivo necesita acceder al mismo servidor; .test solo resuelve en el computador local.</p></details></div>
<div class="case-heading"><div><div class="eyebrow">EXPEDIENTE DE DEMOSTRACIÓN</div><h1>{{ $d['patient'] }}</h1><p class="muted">{{ $case->folio }} · {{ $d['insurance'] }} · {{ $d['days'] }} días solicitados</p></div><div><span class="badge state-{{ $case->status }}">{{ \App\Services\DemoLicenciaService::STATES[$case->status] }}</span><small>Actualizado {{ $case->updated_at->timezone('America/Santiago')->format('d-m-Y H:i') }}</small></div></div>
@php($stage=match($case->status){'borrador'=>0,'paciente','cancelada'=>1,'empleador'=>2,'revision','rechazada','apelacion'=>3,'aprobada','reducida'=>4,default=>5})
<section class="steps">@foreach(['Emisión','Paciente','Empleador','Contraloría','Pago SIL','Completado'] as $step)<div class="{{ $loop->index===$stage?'current':($loop->index<$stage?'complete':'') }}"><span>{{ $loop->index<$stage?'✓':str_pad($loop->iteration,2,'0',STR_PAD_LEFT) }}</span><b>{{ $step }}</b></div>@endforeach</section>
@if($d['hold'])<div class="notice warning"><b>Revisión preventiva pendiente.</b> La emisión, el dictamen y el pago requieren que Auditoría cierre la alerta con un fundamento. Es una señal de ejemplo, no un diagnóstico de fraude.</div>@endif
<div class="case-grid"><div class="main-column">
<section class="panel"><div class="section-head"><div><div class="eyebrow">MESA DE TRABAJO</div><h2>{{ \App\Services\DemoLicenciaService::ROLES[$role] }}</h2></div><span class="badge">Acciones del perfil</span></div>
@if($role==='admin')
<p>Este es el mismo expediente para todos los participantes. Elige un perfil en la barra superior para actuar.</p><div class="next-step"><span>PRÓXIMO PASO</span><strong>{{ match($case->status){'borrador'=>'Profesional: verificar y emitir','paciente'=>'Paciente: autorizar o rechazar el envío','empleador'=>'Empleador: preparar antecedentes','revision','apelacion'=>'Contraloría: resolver el caso','aprobada','reducida'=>'Entidad pagadora: registrar el pago','rechazada'=>'Paciente: presentar reclamación',default=>'Recorrido finalizado; consulta la trazabilidad'} }}</strong></div>
@elseif($role==='profesional')
<p class="muted">{{ $d['doctor'] }} · {{ $d['specialty'] }} · Consulta ficticia en Santiago</p>
<div class="integration-grid"><div><b>{{ $doctorCount }} licencias emitidas en el demo</b><small>Historial del profesional ficticio</small></div><div><b>{{ $doctorMonthCount }} expedientes del mes emitidos</b><small>Cohorte por fecha de creación · solo casos del demo</small></div></div>
<div class="checklist">@foreach(['bono'=>['verified_bono','Bono de atención asociado','Valida el bono de ejemplo antes de emitir.'],'profesional'=>['verified_doctor','Habilitación y especialidad','Simula la consulta del registro profesional.'],'identidad'=>['identity','Identidad y firma del profesional','Confirmación explícita de biometría simulada.']] as $action=>$item)<div><span class="check {{ $d[$item[0]]?'done':'' }}">{{ $d[$item[0]]?'✓':$loop->iteration }}</span><div><b>{{ $item[1] }}</b><small>{{ $item[2] }}</small></div>@if($case->status==='borrador' && !$d[$item[0]])@include('demo.action',['action'=>$action,'label'=>'Simular verificación','style'=>'small secondary','fields'=>[]])@else<span class="badge">{{ $d[$item[0]]?'Verificado · demo':'Pendiente' }}</span>@endif</div>@endforeach</div>
@if($case->status==='borrador')<div class="action-row">@include('demo.action',['action'=>'emitir','label'=>'Emitir licencia y solicitar autorización →','fields'=>[]])</div><p class="fine">La emisión queda registrada en este demo; no crea una LME oficial.</p>@else<div class="notice">La etapa de emisión ya fue registrada. Continúa con el perfil responsable.</div>@endif
@elseif($role==='paciente')
<div class="phone-card"><div class="phone-top">APP DEL PACIENTE <span>Vista web del demo</span></div><h3>Hola, {{ explode(' ',$d['patient'])[0] }}</h3><p>{{ $d['doctor'] }} indicó {{ $d['days'] }} días de reposo desde {{ $d['start'] }}.</p><div class="phone-status">{{ \App\Services\DemoLicenciaService::STATES[$case->status] }}</div>
<p class="fine">Historial de este RUT ficticio: {{ $patientDays }} días autorizados acumulados en los casos del demo (sin descontar superposiciones).</p>
@if($case->status==='paciente')<p>¿Autorizas enviar esta licencia al empleador para preparar tus documentos laborales?</p><div class="action-row">@include('demo.action',['action'=>'autorizar','label'=>'Autorizar envío','fields'=>[]])@include('demo.action',['action'=>'no_autorizar','label'=>'No autorizar','style'=>'secondary','fields'=>[]])</div>@else<p class="fine">Envío al empleador: {{ $d['consent']?'autorizado':'sin autorización' }}.</p>@endif</div>
@if(!in_array($case->status,['borrador','cancelada']))<h3>Tu consentimiento</h3><p class="muted">La ficha crónica de ejemplo solo se muestra a contraloría cuando concedes acceso.</p>@include('demo.action',['action'=>'ficha','label'=>$d['chronic_consent']?'Revocar acceso a ficha crónica':'Autorizar acceso a ficha crónica','style'=>'secondary','fields'=>[]])@endif
@if($d['consent'] && !in_array($case->status,['cancelada','rechazada']))<h3>Control consentido de reposo</h3><form method="POST" action="{{ route('demo.action',$case) }}" class="form-grid">@csrf<input type="hidden" name="version" value="{{ $case->version }}"><input type="hidden" name="action" value="control"><label class="full">Tipo de control<select name="kind"><option value="ubicacion">Simular geolocalización</option><option value="camara">Simular cámara</option></select></label><label class="checkbox full"><input type="checkbox" name="consent_control" value="1" required> Autorizo este control de ejemplo. No se accederá a mi cámara ni a mi ubicación real.</label><button class="button">Registrar control simulado</button></form>@endif
@if(in_array($case->status,['rechazada','reducida']) && $d['appeal_level'] < count($flow->appealSteps($d)))<div class="divider"></div><h3>Presentar una reclamación</h3><p>Siguiente instancia del recorrido: <b>{{ $flow->appealSteps($d)[$d['appeal_level']] }}</b>.</p><form method="POST" action="{{ route('demo.action',$case) }}">@csrf<input type="hidden" name="version" value="{{ $case->version }}"><input type="hidden" name="action" value="apelar"><label>Fundamentos / informe complementario de ejemplo<textarea name="note" minlength="10" maxlength="1000" required placeholder="Describe los nuevos antecedentes ficticios..."></textarea></label><button class="button">Presentar reclamación simulada</button></form>@elseif($case->status==='apelacion')<div class="notice">Tu reclamación está en {{ $d['appeal_entity'] }}. Cambia a Contraloría para resolverla.</div>@endif
@elseif($role==='empleador')
<p><b>{{ $d['employer'] }}</b></p><p class="muted">El empleador recibe los antecedentes laborales. El diagnóstico y la ficha clínica no se muestran en este perfil.</p>
@if(!$d['consent'])<div class="notice warning">Espera la autorización del paciente para preparar documentos.</div>@else<div class="checklist">@foreach(\App\Services\DemoLicenciaService::DOCS as $code=>$name)<div><span class="check {{ isset($d['documents'][$code])?'done':'' }}">{{ isset($d['documents'][$code])?'✓':$loop->iteration }}</span><div><b>{{ $name }}</b><small>Antecedente ficticio del demo</small></div>@if(isset($d['documents'][$code]))<a class="textlink" href="{{ route('demo.document',[$case,$code]) }}" target="_blank">Ver documento ↗</a>@elseif($case->status==='empleador')@include('demo.action',['action'=>'documento','label'=>'Generar ejemplo','style'=>'small secondary','fields'=>['document'=>$code]])@endif</div>@endforeach</div>
@if($case->status==='empleador')<form method="POST" action="{{ route('demo.action',$case) }}">@csrf<input type="hidden" name="version" value="{{ $case->version }}"><input type="hidden" name="action" value="enviar"><label>Promedio mensual neto de los 3 meses (CLP)<input type="number" name="monthly_net" min="100000" max="10000000" value="{{ $d['monthly_net'] }}" required></label><p class="fine">Base ilustrativa ingresada para calcular el subsidio del ejemplo.</p><button class="button">Enviar antecedentes a contraloría →</button></form>@else<div class="notice success">Documentación laboral enviada. El estado se actualiza en este mismo expediente.</div>@endif @endif
@elseif($role==='contraloria')
<p class="muted">{{ $case->status==='apelacion'?$d['appeal_entity']:($d['insurance']==='Fonasa'?'COMPIN':'Isapre') }} · Resolución simulada por revisión humana</p><div class="clinical"><b>Antecedente clínico ficticio</b><p>{{ $d['diagnosis'] }}</p><small>Ficha crónica: {{ $d['chronic_consent']?'acceso autorizado; hipertensión ficticia en control, sin descompensación registrada.':'sin autorización del paciente; acceso restringido.' }}</small></div>
@if($case->status==='revision')<form action="{{ route('demo.action',$case) }}" method="POST" class="form-grid">@csrf<input type="hidden" name="version" value="{{ $case->version }}"><input type="hidden" name="action" value="dictamen"><label>Dictamen<select name="decision"><option value="aprobada">Aprobar totalidad</option><option value="reducida">Reducir días</option><option value="rechazada">Rechazar</option></select></label><label>Días si se reduce<input type="number" name="approved_days" min="1" max="{{ max(1,$d['days']-1) }}" value="{{ min(7,max(1,$d['days']-1)) }}"></label><label class="full">Fundamento del dictamen<textarea name="note" required minlength="10" maxlength="1000" placeholder="Explica la resolución de este caso ficticio..."></textarea></label><button class="button full">Registrar dictamen</button></form>
@elseif($case->status==='apelacion')<div class="notice"><b>Fundamento del paciente:</b> {{ $d['appeal_reason'] }}</div><form action="{{ route('demo.action',$case) }}" method="POST">@csrf<input type="hidden" name="version" value="{{ $case->version }}"><input type="hidden" name="action" value="resolver"><label>Resolución<select name="decision"><option value="acoger">Acoger y autorizar los días solicitados</option><option value="mantener">Mantener dictamen anterior</option></select></label><label>Fundamento<textarea name="note" required minlength="10" maxlength="1000"></textarea></label><button class="button">Resolver reclamación simulada</button></form>
@else<div class="notice">No hay un dictamen ni una reclamación pendiente en esta etapa.</div>@endif
@elseif($role==='pagador')
@php($sil=$flow->subsidy($d))<h3>Liquidación ilustrativa del SIL</h3><div class="calculation"><div>Promedio neto mensual<b>${{ number_format($d['monthly_net'],0,',','.') }}</b></div><div>Base diaria (promedio / 30)<b>${{ number_format($sil['daily'],2,',','.') }}</b></div><div>Días autorizados / carencia<b>{{ $d['approved_days'] ?? 'Pendientes' }} / {{ $sil['waiting'] }} días</b></div><div>Días con subsidio<b>{{ $sil['paid_days'] }}</b></div><div class="total">Monto de ejemplo<b>${{ number_format($sil['amount'],0,',','.') }}</b></div></div><p class="fine">Enfermedad común del sector privado; sin topes, cotizaciones ni continuidad. No es una liquidación oficial.</p>
@if(in_array($case->status,['aprobada','reducida']))@include('demo.action',['action'=>'pagar','label'=>'Registrar pago simulado','fields'=>[]])@elseif($case->status==='pagada')<div class="notice success">Pago registrado una sola vez. No se realizó ninguna transferencia bancaria.</div><a class="button" href="{{ route('demo.receipt',$case) }}" target="_blank">Ver comprobante imprimible ↗</a>@else<div class="notice">El pago se habilita después de una resolución favorable.</div>@endif
@elseif($role==='auditor')
<p class="muted">Simula señales de emisión inusual, credenciales o inconsistencias entre fuentes. Una alerta solicita revisión; no declara fraude.</p><div class="integration-grid">@foreach(['Registro profesional','SII / Dirección del Trabajo','Control migratorio PDI','Patrones de emisión'] as $source)<div><b>{{ $source }}</b><small>Fuente simulada · sin conexión externa</small></div>@endforeach</div>
@if(!in_array($case->status,['pagada','cancelada']))<form method="POST" action="{{ route('demo.action',$case) }}">@csrf<input type="hidden" name="version" value="{{ $case->version }}"><input type="hidden" name="action" value="{{ $d['hold']?'liberar':'alerta' }}"><label>{{ $d['hold']?'Fundamento de la revisión humana':'Señal de riesgo de ejemplo' }}<textarea name="note" minlength="10" maxlength="1000" required placeholder="{{ $d['hold']?'Antecedentes revisados; inconsistencia de ejemplo aclarada.':'Ejemplo: frecuencia de emisión fuera del patrón de referencia.' }}"></textarea></label><button class="button {{ $d['hold']?'':'secondary' }}">{{ $d['hold']?'Cerrar alerta y permitir continuidad':'Abrir revisión preventiva simulada' }}</button></form>@endif
@endif
</section>
@if(isset($d['resolution']) && $role!=='empleador')<section class="panel"><div class="eyebrow">ÚLTIMA RESOLUCIÓN</div><h3>{{ \App\Services\DemoLicenciaService::STATES[$case->status] }}</h3><p>{{ $d['resolution'] }}</p><span class="badge">{{ $d['approved_days'] }} de {{ $d['days'] }} días autorizados</span></section>@endif
<section class="panel"><div class="section-head"><div><div class="eyebrow">REGISTRO COMPARTIDO</div><h2>Trazabilidad del expediente</h2></div><span class="badge">{{ count($d['events']) }} eventos</span></div><ol class="timeline">@foreach(array_reverse($d['events']) as $event)<li><span class="timeline-dot"></span><div><div class="event-meta">{{ $event['role'] }} · {{ $event['source'] ?? 'Portal web' }} <time>{{ $event['at'] }}</time></div><b>{{ $role==='empleador' && in_array($event['role'],['Contraloría','Paciente'])?'Actualización de estado registrada':$event['label'] }}</b>@if($event['note'] && $role!=='empleador')<p>{{ $event['note'] }}</p>@endif</div></li>@endforeach</ol></section>
</div><aside class="side-column"><section class="panel"><div class="eyebrow">IDENTIFICACIÓN</div><h3>{{ $case->folio }}</h3><dl><dt>Paciente</dt><dd>{{ $d['patient'] }}</dd><dt>RUT ficticio</dt><dd>{{ $d['rut'] }}</dd><dt>Inicio / término</dt><dd>{{ $d['start'] }} / {{ \Carbon\Carbon::parse($d['start'])->addDays($d['days']-1)->toDateString() }}</dd><dt>Reposo solicitado</dt><dd>{{ $d['days'] }} días</dd><dt>Profesional</dt><dd>{{ $d['doctor'] }}</dd><dt>Bono asociado</dt><dd>{{ $d['bono'] }}</dd></dl><div class="qr-block"><canvas id="qr" aria-label="QR verificable del expediente"></canvas><a class="textlink" href="{{ route('demo.verify',$d['token']) }}" target="_blank">Abrir verificación QR ↗</a><small>Verificación local de ejemplo.<br>En otro dispositivo requiere acceso al servidor.</small></div></section>
<section class="panel"><div class="eyebrow">PROPUESTA SDI</div><h3>¿Y si se pagara desde el día 1?</h3>@php($base=$flow->subsidy($d))@php($proposal=$flow->subsidy($d,true))<p class="fine">Comparación ilustrativa sobre {{ $base['days'] }} días. Es una propuesta del PowerPoint, no una regla vigente aplicada al pago.</p><div class="compare"><div><span>Regla base del ejemplo</span><b>${{ number_format($base['amount'],0,',','.') }}</b><small>{{ $base['paid_days'] }} días con subsidio</small></div><div><span>Propuesta día 1</span><b>${{ number_format($proposal['amount'],0,',','.') }}</b><small>{{ $proposal['paid_days'] }} días con subsidio</small></div></div></section>
<section class="panel"><h3>Documentación</h3>@forelse($d['documents'] as $code=>$document)<a class="document-link" href="{{ route('demo.document',[$case,$code]) }}" target="_blank">{{ $document['name'] }} ↗</a>@empty<p class="muted">El empleador aún no incorpora antecedentes.</p>@endforelse @if($case->status==='pagada')<a class="document-link" href="{{ route('demo.receipt',$case) }}" target="_blank">Comprobante de pago simulado ↗</a>@endif</section>
@if(count($d['controls']))<section class="panel"><h3>Controles consentidos</h3>@foreach($d['controls'] as $control)<p><b>{{ ucfirst($control['type']) }}</b><small>{{ $control['result'] }}</small></p>@endforeach</section>@endif
</aside></div>
@endsection
@section('scripts')<script src="{{ asset('demo-assets/qrious.min.js') }}"></script><script>if(window.QRious){new QRious({element:document.getElementById('qr'),value:@json(route('demo.verify',$d['token'])),size:180,level:'M',foreground:'#173b42'});}</script>@endsection
